services:
  db:
    image: mysql:8.0
    container_name: mysql_db_2
    restart: unless-stopped
    command: --log-bin-trust-function-creators=1 --lower-case-table-names=1
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: foxday
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "13308:3306"
    volumes:
      - db_data:/var/lib/mysql  # Use named volume instead
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container_2
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: admin
      UPLOAD_LIMIT: 100M
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
